name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install backend
        run: npm install
      - name: npm install frontend
        working-directory: './frontend'
        run: npm install
      - name: build frontend
        working-directory: './frontend'
        run: npm run build
      - name: remove old build from backend
        run: rm -rf build
      - name: move build to backend
        working-directory: './frontend'
        run: mv './build' '../'
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phonebook-anna" #Must be unique in Heroku
          heroku_email: "anna.nikander@aalto.fi"
          remote_branch: master
          healthcheck: "https://phonebook-anna.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      #- name: test
        #run: npm run test
      #- name: e2e tests
        #uses: cypress-io/github-action@v2
        #with:
          #command: npm run test:e2e
          #start: npm run start-prod
          #wait-on: http://localhost:5000